# From the population by race group https://api.census.gov/data/2018/acs/acs5/groups/B03002.html
GROUP_HISPANIC_OR_LATINO_ORIGIN_BY_RACE = "B03002"

# TODO: Consider shifting to B25003[A-I]_003E to get renter households
# by race and compute fractions from those instead of overall population.
# https://api.census.gov/data/2017/acs/acs5/groups/B25003A.html through
# https://api.census.gov/data/2017/acs/acs5/groups/B25003I.html.

# The counts of renters by race and ethicity are in different groups,
# one per ethnicity.
GROUP_TENURE_ALL = "B25003"
GROUP_TENURE_WHITE = "B25003A"
GROUP_TENURE_BLACK = "B25003B"
GROUP_TENURE_AMERICAN_INDIAN_ALASKAN_NATIVE = "B25003C"
GROUP_TENURE_ASIAN = "B25003D"
GROUP_TENURE_NATIVE_HAWAIIAN_OTHER_PACIFIC_ISLANDER = "B25003E"
GROUP_TENURE_SOME_OTHER_ALONE = "B25003F"
GROUP_TENURE_TWO_INCLUDING_SOME_OTHER = "B25003G"
GROUP_TENURE_TWO_EXCLUDING_SOME_OTHER_OR_THREE = "B25003H"
GROUP_TENURE_HISPANIC_LATINO = "B25003I"

TENURE_BY_RACE_GROUPS = [
    GROUP_TENURE_WHITE,
    GROUP_TENURE_BLACK,
    GROUP_TENURE_AMERICAN_INDIAN_ALASKAN_NATIVE,
    GROUP_TENURE_ASIAN,
    GROUP_TENURE_NATIVE_HAWAIIAN_OTHER_PACIFIC_ISLANDER,
    GROUP_TENURE_SOME_OTHER_ALONE,
    GROUP_TENURE_TWO_INCLUDING_SOME_OTHER,
    GROUP_TENURE_TWO_EXCLUDING_SOME_OTHER_OR_THREE,
    GROUP_TENURE_HISPANIC_LATINO,
]

_RENTER_ESTIMATE = "003E"
VARIABLE_TOTAL_RENTERS = f"{GROUP_TENURE_ALL}_{_RENTER_ESTIMATE}"
VARIABLES_FOR_RENTERS = [
    f"{group}_{_RENTER_ESTIMATE}" for group in TENURE_BY_RACE_GROUPS
]

GROUP_POPULATION = "B03002"
VARIABLE_TOTAL_POPULATION = "B03002_001E"
TOTAL_HISPANIC_OR_LATINO = "B03002_012E"

# From income by tenure group https://api.census.gov/data/2018/acs/acs5/groups/B25119.html
GROUP_MEDIAN_HOUSEHOLD_INCOME_BY_TENURE = "B25119"

MEDIAN_HOUSEHOLD_INCOME_FOR_RENTERS = "B25119_003E"
